name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            set -e  # Exit if any command fails

            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
            nvm use --lts

            cd /root/zenova-psychology
            git pull origin main

            #### FRONTEND BUILD ####
            echo "STRAPI_BEARER_TOKEN=${{ secrets.STRAPI_BEARER_TOKEN }}" >> .env.local
            echo "REVALIDATION_KEY=${{ secrets.REVALIDATION_KEY }}" >> .env.local
            echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" >> .env.local

            npm install
            npm run build
            pm2 restart zenova_frontend
          EOF
